version: '3'
services:
  web:
    build: ./docker/web/
    container_name: "web"
    volumes:  
      - ./src/:/var/www/html/
    depends_on:
      - mysql
    ports:
      - "8080:80"
    tty: true

  mysql:
    build: ./docker/mysql
    container_name: "mysql"
    env_file: ./.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/storage/data/mysql:/var/lib/mysql